version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "assembly"
      POSTGRES_DB: "assembly"
    volumes:
      - "./assets/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"

    ports:
      - "5432:5432"